CREATE DATABASE 8BITGAME;

SELECT 8BITGAME
CREATE TABLE ACCOUNT (
  ACCOUNT_ID INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  ACCOUNT_Email VARCHAR(50) NOT NULL,
  ACCOUNT_EmailVerifcation binary(1) NOT NULL,
PRIMARY KEY(ACCOUNT_ID)
);

CREATE TABLE PRODUCT (
  PRODUCT_ID INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  PRODUCT_Type VARCHAR(50) NOT NULL,
  PRODUCT_Title VARCHAR(50) NOT NULL,
  PRODUCT_Price INT(11) NOT NULL,
  PRODUCT_Version VARCHAR(20) NOT NULL,
PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE NEWS (
  ARTICLE_ID INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  ARTICLE_Title VARCHAR(50) NULL,
  ARTICLE_Category VARCHAR(50) NULL,
  ARTICLE_Date DATE NULL,
  ARTICLE_Message VARCHAR(50) NULL,
PRIMARY KEY(ARTICLE_ID)
);

CREATE TABLE PROFILE (
  PROFILE_ID INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  PROFILE_Password VARCHAR(30) NOT NULL,
  PROFILE_DOB DATE NOT NULL,
  PROFILE_DateRegistered DATE NOT NULL,
  PROFILE_UserType integer(11) NOT NULL,
  PROFILE_AccountStatus integer(11) NOT NULL,
  PROFILE_PurchaseHistory VARCHAR(200) NULL,
  ACCOUNT_ID INT,
PRIMARY KEY(PROFILE_ID),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE ORDER (
  ORDER_ID INT(11) NOT NULL UNIQUE AUTO_INCREMENT,
  ORDER_CreiditCard INT(20) NOT NULL UNIQUE,
  ORDER_ExpiryDate DATE NOT NULL,
  ORDER_SecurityNumber INT(6) NOT NULL,
  ORDER_NameOnCard VARCHAR(200) NOT NULL,
  ORDER_DATE DATE NOT NULL,
  ACCOUNT_ID INT,
  PRODUCT_ID INT,
PRIMARY KEY(ORDER_ID),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

//CREATED BY 21600681 TEAM B